apiVersion: v1
kind: Pod
metadata:
  name: kayaclaw
  namespace: dev
  labels:
    app: kudams
spec:
  restartPolicy: Never
  containers:
  - name: claw
    image: registry.ai-application.garage.dubai/kayaclaw:latest
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-storage
      mountPath: /var/lib/docker
    ports:
      - name: http
        containerPort: 8000
        protocol: TCP
    resources:
        limits:
          cpu: 4000m
          memory: 4Gi
        requests:
          cpu: 2000m
          memory: 2Gi
  volumes:
  - name: docker-storage
    persistentVolumeClaim:
      claimName: dockerfile-pvc
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: dockerfile-pvc
#   namespace: dev
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: nfs-csi

---
apiVersion: v1
kind: Service
metadata:
  name: kayaclaw-svc
  namespace: dev
  labels:
    app: kudams
spec:
  type: ClusterIP
  ports:
    - port: 18789
      targetPort: 18789
      protocol: TCP
      name: http
  selector:
    app: kudams
